// Interface copy only. Street names, staff notes and place names stay as recorded.
export const filipino: Record<string, string> = {
  'No matching reachable shelters. Change the starting point or filters.':
    'Walang tugmang masisilungang mararating. Suriin ang lokasyon o mga filter.',
  'Waiting for CDRRMO to publish verified shelters.':
    'Hinihintay ang CDRRMO na maglathala ng nasuring masisilungan.',
  'No shelters match your search.': 'Walang masisilungang tugma sa paghahanap.',
  'Reported street hazards': 'Mga iniulat na panganib sa kalsada',
  'Hidden map layers still affect routing.':
    'Kasama sa pagsusuri ng ruta kahit ang mga panganib na nakatago sa mapa.',
  'No active street reports have been published. This does not confirm that streets are safe.':
    'Walang aktibong ulat na nailathala. Hindi nito tinitiyak na ligtas ang mga kalsada.',
  'Santa Rosa streets · awaiting CDRRMO data':
    'Mga kalsada ng Santa Rosa · hinihintay ang datos ng CDRRMO',
  'Routes use the latest available road and hazard reports':
    'Batay ang ruta sa pinakahuling makuhang ulat ng kalsada at panganib',
  'Show official boundaries': 'Ipakita ang mga hangganan',
  'No verified boundary dataset is loaded': 'Walang nasuring datos ng hangganan',
  Blocked: 'Sarado',
  Affected: 'Apektado',
  'Road closure': 'Saradong kalsada',
  'Your selected starting point': 'Ang napiling lokasyon mo',
  'Delivery could not be confirmed. Please retry.':
    'Hindi matiyak na natanggap ang kahilingan. Subukan muli.',
  'Find Shelter Now': 'Humanap ng masisilungan',
  'Use my location': 'Gamitin ang lokasyon ko',
  'Finding location…': 'Hinahanap ang lokasyon…',
  'Finding your current location…': 'Hinahanap ang lokasyon mo…',
  'Choose your starting point': 'Piliin ang lokasyon mo',
  'Your current location': 'Kasalukuyang lokasyon mo',
  'Selected map location': 'Napiling lokasyon sa mapa',
  'Entered location': 'Inilagay na lokasyon',
  'Select a location on the map': 'Pumili ng lokasyon sa mapa',
  'Where are you now?': 'Nasaan ka ngayon?',
  'YOUR STARTING POINT': 'ANG LOKASYON MO',
  'YOUR WAY TO SAFETY': 'DAAN PAPUNTA SA MASISILUNGAN',
  'A safer route starts here': 'Magsimula sa mas ligtas na ruta',
  'Find an available shelter and a route that considers the hazards around you.':
    'Humanap ng masisilungan at rutang isinasaalang-alang ang mga panganib sa paligid.',
  'Evacuation map': 'Mapa ng paglikas',
  Shelters: 'Mga masisilungan',
  Shelter: 'Masisilungan',
  Hazards: 'Mga panganib',
  'How it works': 'Paano gamitin',
  'Emergency help': 'Tulong sa emerhensiya',
  'Use light theme': 'Maliwanag na tema',
  'Use dark theme': 'Madilim na tema',
  'EVACUATION SUPPORT': 'GABAY SA PAGLIKAS',
  'Prepared together. Safer together.': 'Sama-samang maghanda para sa kaligtasan.',
  Offline: 'Walang koneksiyon',
  'Saved data': 'Naka-save na datos',
  'Awaiting CDRRMO setup': 'Hinihintay ang datos ng CDRRMO',
  Connected: 'May koneksiyon',
  'CDRRMO reports and verified shelters are not available yet. Street maps remain available; no evacuation routes can be generated until shelters are published.':
    'Wala pang ulat at masisilungang inilathala ang CDRRMO. Magagamit ang mapa, ngunit kailangan muna ng datos ng masisilungan para makahanap ng ruta.',
  'CDRRMO panel': 'Panel ng CDRRMO',
  'You’re offline.': 'Wala kang koneksiyon.',
  'Live updates unavailable.': 'Hindi makakuha ng bagong datos.',
  'Data may be out of date.': 'Maaaring luma na ang datos.',
  'No saved data is available yet.': 'Wala pang naka-save na datos.',
  'Map tiles may be unavailable.': 'Maaaring hindi lumabas ang mapa.',
  Retry: 'Subukan muli',
  'Offline storage is unavailable in this browser. Keep this page open to retain the current view.':
    'Hindi makapag-save sa browser na ito. Panatilihing bukas ang pahina upang makita ang kasalukuyang datos.',
  'Routes consider all active hazards': 'Isinasaalang-alang ang lahat ng aktibong panganib',
  'Recommended shelters': 'Mga mungkahing masisilungan',
  'Nearby shelters': 'Mga kalapit na masisilungan',
  'Risk + distance': 'Panganib + layo',
  'Select a start to rank': 'Piliin muna ang lokasyon mo',
  'Search shelters or barangays': 'Maghanap ng masisilungan o barangay',
  'Search shelter or barangay': 'Hanapin ang masisilungan o barangay',
  'Step-free shelter access only': 'Mga masisilungang walang hagdan sa pasukan lamang',
  'Loading shelter information…': 'Kinukuha ang datos ng masisilungan…',
  'Unable to load shelters. Reconnect and try again.':
    'Hindi makuha ang datos. Kumonekta at subukan muli.',
  'No matching reachable shelters. Try changing your search or starting point.':
    'Walang tugmang masisilungang mararating. Baguhin ang paghahanap o lokasyon.',
  'Blocked street': 'Saradong kalsada',
  'Affected street': 'Apektadong kalsada',
  'Risk-aware guidance. Stay aware of your surroundings.':
    'Gabay batay sa mga ulat. Mag-ingat sa iyong paligid.',
  'WALKING ROUTE': 'RUTA SA PAGLALAKAD',
  'Exit navigation': 'Isara ang gabay sa ruta',
  Boundaries: 'Mga hangganan',
  'Preparing your map…': 'Inihahanda ang mapa…',
  'Map data unavailable': 'Hindi makuha ang mapa',
  'Try again': 'Subukan muli',
  flood: 'baha',
  fire: 'sunog',
  earthquake: 'lindol',
  'Tap the map to set your starting point': 'Pindutin ang mapa upang piliin ang lokasyon mo',
  'Cancel location selection': 'Kanselahin ang pagpili ng lokasyon',
  'Your safety. A clear direction.': 'Malinaw na gabay sa paglikas.',
  'Choose your location to see routes to available shelters.':
    'Piliin ang lokasyon mo upang makita ang ruta sa masisilungan.',
  'Walking route': 'Ruta sa paglalakad',
  'Lower-risk route': 'Rutang may mas mababang panganib',
  'SUGGESTED ROUTE': 'MUNGKAHING RUTA',
  'Clear route': 'Alisin ang ruta',
  'Est. walking time': 'Tantiyang oras ng lakad',
  'Route distance': 'Haba ng ruta',
  'Low risk': 'Mababang panganib',
  'Elevated risk': 'Mas mataas na panganib',
  'Open navigation map': 'Buksan ang gabay sa mapa',
  'Show entire route': 'Ipakita ang buong ruta',
  'Directions from your selected starting point; position is not tracked live.':
    'Gabay mula sa napiling lokasyon; hindi tuloy-tuloy na sinusubaybayan ang lokasyon mo.',
  'Streets to the shelter': 'Mga kalsada papunta sa masisilungan',
  'Start on': 'Magsimula sa',
  'Continue onto': 'Magpatuloy sa',
  'Continue along': 'Magpatuloy sa',
  'Blocked street segments — avoided': 'Mga saradong bahagi ng kalsada — iniiwasan',
  'Red sections are blocked. Other sections of the same street may remain open.':
    'Sarado ang mga pulang bahagi. Maaaring bukas pa ang ibang bahagi ng kalsada.',
  'Route details and limitations': 'Detalye at limitasyon ng ruta',
  'Refresh data': 'I-update ang datos',
  'Available shelters': 'Mga bukas na masisilungan',
  'accepting evacuees': 'tumatanggap ng lilikas',
  'Reported capacity': 'Iniulat na kapasidad',
  'spaces available': 'bakanteng puwesto',
  'Street hazard reports': 'Mga ulat ng panganib sa kalsada',
  'included in route checks': 'kasama sa pagsusuri ng ruta',
  'Helping Santa Rosa move toward safety.': 'Gabay sa paglikas ng Santa Rosa.',
  'Community evacuation support': 'Gabay sa paglikas ng komunidad',
  'About this system': 'Tungkol sa sistema',
  'Dismiss message': 'Isara ang mensahe',
  'RECOMMENDED FOR YOU': 'IMINUMUNGKAHI PARA SA IYO',
  Open: 'Bukas',
  Closed: 'Sarado',
  Full: 'Puno',
  'Near full': 'Halos puno',
  'Not accepting': 'Hindi muna tumatanggap',
  'Step-free': 'Walang hagdan sa pasukan',
  'Step-free shelter entrance': 'Pasukan na walang hagdan',
  'Facilities and access': 'Pasilidad at pasukan',
  'Step-free entrance reported. Route accessibility has not been assessed.':
    'Iniulat na walang hagdan sa pasukan. Hindi pa nasuri ang accessibility ng buong ruta.',
  'Step-free access has not been confirmed.': 'Hindi pa tiyak kung walang hagdan sa pasukan.',
  'Enter a location by coordinates': 'Ilagay ang latitude at longitude',
  'Use this starting point': 'Gamitin ang lokasyong ito',
  'Find your way to safety': 'Gabay sa paglikas',
  'Close help': 'Isara ang tulong',
  'Choose your starting point.': 'Piliin ang lokasyon mo.',
  'Use your location or select a point on the map.': 'Gamitin ang lokasyon mo o pumili sa mapa.',
  'Find a shelter.': 'Humanap ng masisilungan.',
  'Routes consider flood, fire, earthquake exposure, road conditions, and available capacity.':
    'Isinasaalang-alang ang baha, sunog, lindol, kondisyon ng kalsada at bakanteng puwesto.',
  'Check conditions as you go.': 'Suriin ang paligid habang lumilikas.',
  'Recorded data can be incomplete. Follow official evacuation instructions.':
    'Maaaring kulang ang datos. Sundin ang opisyal na tagubilin sa paglikas.',
  'Need immediate assistance?': 'Kailangan ng agarang tulong?',
  'Contact local emergency responders or the nearest barangay office. This app does not dispatch assistance.':
    'Makipag-ugnayan sa lokal na responders o pinakamalapit na barangay. Hindi nagdidispatch ng tulong ang app na ito.',
  'Your browser asks permission before sharing your location with this page; your position is not saved or uploaded automatically.':
    'Hihingi ng pahintulot ang browser bago gamitin ang lokasyon mo. Hindi ito awtomatikong ise-save o ipapadala.',
  'Got it': 'Naiintindihan ko',
  'Automatic location needs HTTPS or localhost. You can still choose your starting point manually.':
    'Kailangan ng ligtas na koneksiyon para awtomatikong makita ang lokasyon. Maaari kang pumili sa mapa.',
  'Location is unavailable. Choose a point on the map instead.':
    'Hindi makita ang lokasyon. Pumili sa mapa.',
  'Location permission was denied or a position could not be found. Choose a point on the map.':
    'Walang pahintulot o hindi makita ang lokasyon. Pumili sa mapa.',
  'Select your starting point on the map, or use your current location.':
    'Piliin ang lokasyon mo sa mapa o gamitin ang kasalukuyang lokasyon.',
  'Your starting point is outside the loaded Santa Rosa road coverage. Choose a point inside the mapped area.':
    'Nasa labas ng sakop na mapa ang lokasyon mo. Pumili sa loob ng sakop ng Santa Rosa.',
  'No reachable shelter was found in this road network. Try another starting point or contact local responders.':
    'Walang masisilungang mararating sa nakatalang mga kalsada. Tiyakin ang lokasyon mo o makipag-ugnayan sa responders.',
  'Choose your starting point to calculate a route to this shelter.':
    'Piliin muna ang lokasyon mo upang makahanap ng ruta.',
  'This shelter is full, closed, exposed to a severe hazard, or has no reachable route.':
    'Maaaring puno, sarado, nasa panganib o walang madaanan papunta sa masisilungang ito.',
  'Automatically notify CDRRMO with this location if no suitable route is found':
    'Ipaalam sa CDRRMO ang lokasyong ito kung walang makitang angkop na ruta',
  'No suitable route? Request assistance': 'Walang angkop na ruta? Humiling ng tulong',
  'Contact number or name (optional)': 'Numero o pangalan (opsyonal)',
  'Situation or nearby landmark (optional)': 'Sitwasyon o kalapit na palatandaan (opsyonal)',
  'Sending request…': 'Ipinapadala ang kahilingan…',
  'Request received': 'Natanggap ang kahilingan',
  'Retry assistance request': 'Ipadala muli ang kahilingan',
  'Share location and notify CDRRMO': 'Ipadala ang lokasyon sa CDRRMO',
  'Reporting is not available until CDRRMO setup is complete.':
    'Magagamit ang pag-uulat kapag handa na ang sistema ng CDRRMO.',
  'You are offline. The request has not been sent. Connect and retry, or contact local responders directly.':
    'Walang koneksiyon. Hindi naipadala ang kahilingan. Kumonekta at subukan muli o direktang makipag-ugnayan sa responders.',
  'Request received by the CDRRMO system. This does not confirm that a responder has seen it or that help has been dispatched.':
    'Natanggap ng sistema ng CDRRMO ang kahilingan. Hindi pa nito tinitiyak na nabasa ito ng responder o may paparating na tulong.',
  'Drinking water': 'Inuming tubig',
  Food: 'Pagkain',
  'First aid': 'Paunang lunas',
  unknown: 'hindi pa naiulat',
  adequate: 'sapat',
  low: 'kaunti',
  unavailable: 'wala',
  'Entrance checked by staff': 'Pasukang nasuri ng kawani',
  'Entrance not yet verified': 'Hindi pa nasusuri ang pasukan',
  'Last shelter update': 'Huling ulat ng masisilungan',
  'No update time reported': 'Walang oras ng ulat',
  'Shelter information is over 24 hours old. Confirm with staff.':
    'Mahigit 24 oras na ang ulat. Kumpirmahin sa kawani.',
};
